module.exports = [
    {code:1,name:"비씨"},
    {code:2,name:"국민"},
    {code:3,name:"하나(외환)"},
    {code:4,name:"삼성"},
    {code:6,name:"신한"},
    {code:7,name:"현대"},
    {code:8,name:"롯데"},
    {code:11,name:"씨티"},
    {code:12,name:"NH채움"},
    {code:13,name:"수협"},
    {code:14,name:"신협"},
    {code:15,name:"우리카드"},
    {code:21,name:"광주"},
    {code:22,name:"전북"},
    {code:23,name:"제주"},
    {code:24,name:"산은캐피탈"},
    {code:25,name:"해외 비자"},
    {code:26,name:"해외 마스터"},
    {code:27,name:"해외 다이너스"},
    {code:28,name:"해외 AMX"},
    {code:29,name:"해외 JCB"},
    {code:31,name:"OKCashbag"},
    {code:32,name:"우체국"},
    {code:33,name:"MG새마을 체크카드"},
    {code:34,name:"중국은행 체크카드"},
    {code:35,name:"KDB 체크카드"},
    {code:36,name:"현대증권 체크카드"},
    {code:37,name:"저축은행"}
];